# Change these first
owner: TigreGotico # Your GitHub organization or username, where this repository lives
repo: public-servers # The name of this repository

sites:
  - name: HiveMind - demo chat
    url: https://demo.hivemind.tigregotico.pt
  - name: TTS - NOS
    url: https://nos.tigregotico.pt/status
  - name: TTS - Matxa
    url: https://matxa.tigregotico.pt/status
  - name: TTS - Piper
    url: https://piper.tigregotico.pt/status
  - name: TTS - Mimic
    url: https://mimic.tigregotico.pt/status
  - name: TTS - SAM
    url: https://sam.tigregotico.pt/status
  - name: STT - FasterWhisper (turbo-v3)
    url: https://fasterwhisper.tigregotico.pt/status
  - name: STT - Citrinet
    url: https://citrinet.tigregotico.pt/status
  - name: STT - Vosk
    url: https://vosk.tigregotico.pt/status
  - name: STT - Google Chromium (proxy)
    url: https://chromium.tigregotico.pt/status
  - name: Translate - NLLB
    url: https://nllb.tigregotico.pt/status
  - name: Translate - Google (proxy)
    url: https://google-translate.tigregotico.pt/status
  - name: Persona - Qwen2.5
    url: https://qwen.tigregotico.pt/status
  - name: Persona - Phi4
    url: https://phi4.tigregotico.pt/status
  - name: Persona - Mixtral (proxy)
    url: https://mixtral.tigregotico.pt/status
  - name: Persona - Claude (proxy)
    url: https://claude.tigregotico.pt/status
  - name: Persona - GPT-4o-mini (proxy)
    url: https://gpt4.tigregotico.pt/status
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /public-servers
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Tigre Gótico Server Status"
  introTitle: "Welcome to **Tigre Gótico Lda** public servers uptime monitor page"
  introMessage: This page uses **real-time** data from our [GitHub repository](https://github.com/TigreGotico/public-servers). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
